import json
from typing import List, Dict, Any
from services.llm_service import llm_service
from utils.logger import app_logger

class ReviewerAgent:
    def review_violations(self, violations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Synthesizes the findings of the specialized agents. Identifies and removes
        hallucinations, merges duplicates, and checks classification consistency.
        """
        if not violations:
            return []
            
        app_logger.info(f"Reviewer Agent checking consensus on {len(violations)} alerts...")
        
        # Prepare list for LLM context
        violations_input = []
        for i, v in enumerate(violations):
            violations_input.append({
                "index": i,
                "page": v["page_number"],
                "category": v["category"],
                "entity_type": v.get("entity_type"),
                "severity": v["severity"],
                "snippet": v.get("snippet", ""),
                "reason": v.get("reason", "")
            })
            
        # Formulate consensus review prompt
        prompt = f"""You are the Lead Compliance Reviewer and Auditor in a Multi-Agent Consensus System.
Your task is to audit a list of compliance alerts generated by individual automated agents scanning a PDF document.

Analyze the alerts for:
1. Hallucination Risk: Ensure the snippet matches the reported reason. If the snippet is empty or completely unrelated, flag as false positive.
2. Duplicate Warnings: Merge alerts that flag the same or overlapping text blocks on the same page.
3. Classification Consistency: Validate that the severity level (LOW, MEDIUM, HIGH, CRITICAL) matches the risk. For example, a credit card exposure should be HIGH, and a single email should be MEDIUM. Correct them if wrong.

Here is the list of alerts generated by the agents:
{json.dumps(violations_input, indent=2)}

You MUST output a strictly formatted JSON array containing the indices of the APPROVED/VALIDATED alerts, optionally with updated severity or comments.
Output format:
{{
  "consensus_achieved": true,
  "approved_alerts": [
    {{
      "index": 0,
      "approved": true,
      "updated_severity": "MEDIUM",
      "auditor_notes": "Alert validated. Standard email leak."
    }},
    {{
      "index": 1,
      "approved": false,
      "auditor_notes": "Rejected. Hallucination: Snippet does not contain credit card digits."
    }}
  ]
}}

Provide output ONLY as valid JSON.
"""
        
        try:
            result = llm_service.invoke_model(
                prompt=prompt,
                model_type="complex",  # Claude Sonnet for consensus reasoning
                temperature=0.0
            )
            
            approved_actions = {item["index"]: item for item in result.get("approved_alerts", [])}
            
            approved_violations = []
            for i, v in enumerate(violations):
                action = approved_actions.get(i)
                if action and action.get("approved", True):
                    # Apply updates if any
                    v_copy = v.copy()
                    if "updated_severity" in action and action["updated_severity"]:
                        v_copy["severity"] = action["updated_severity"]
                    # Add reviewer feedback notes
                    v_copy["reviewer_notes"] = action.get("auditor_notes", "Alert approved by consensus agent.")
                    approved_violations.append(v_copy)
                else:
                    app_logger.info(f"Consensus Agent filtered out violation at index {i}: Category={v['category']}, Snippet='{v.get('snippet')}'")
                    
            app_logger.info(f"Consensus review complete. Approved {len(approved_violations)} of {len(violations)} alerts.")
            return approved_violations
            
        except Exception as e:
            app_logger.error(f"Reviewer Agent consensus verification failed: {e}. Defaulting to approving all original alerts.")
            # Default fallback: trust the original agents
            return violations

# Global agent instantiator
reviewer_agent = ReviewerAgent()
